### ISSUE TITLE
Benthos crashes using custom Plugin

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [redpanda-data/benthos#12]
Not sure why but using my custom `Process`, Benthos is crashing with:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb7593d]

goroutine 358 [running]:
github.com/redpanda-data/benthos/v4/public/service.(*airGapProcessor).Process(0xc001ba9250, {0x5d45170, 0xc0022328c0}, 0xc001dd9518)
	/go/pkg/mod/github.com/redpanda-data/benthos/v4@v4.28.1/public/service/processor.go:81 +0xdd
github.com/redpanda-data/benthos/v4/internal/component/processor.(*v2ToV1Processor).ProcessBatch.func1(0x457b89?, 0xc001dd9518)
	/go/pkg/mod/github.com/redpanda-data/benthos/v4@v4.28.1/internal/component/processor/auto_observed.go:97 +0xad
github.com/redpanda-data/benthos/v4/internal/message.Batch.Iter({0xc001475b10, 0x1, 0x0?}, 0xc000e9bba0)
	/go/pkg/mod/github.com/redpanda-data/benthos/v4@v4.28.1/internal/message/message.go:70 +0x103
github.com/redpanda-data/benthos/v4/internal/component/processor.(*v2ToV1Processor).ProcessBatch(0xc001ab8f30, {0x5d45170, 0xc0022328c0}, {0xc001475b10, 0x1, 0x1})
	/go/pkg/mod/github.com/redpanda-data/benthos/v4@v4.28.1/internal/component/processor/auto_observed.go:94 +0x11f
github.com/redpanda-data/benthos/v4/internal/component/processor.ExecuteAll({0x5d45170, 0xc0022328c0}, {0xc001ab6f00, 0x2, 0x9671c0?}, {0xc002754dc8?, 0x1, 0x3?})
	/go/pkg/mod/github.com/redpanda-data/benthos/v4@v4.28.1/internal/component/processor/execute.go:19 +0x1c7
github.com/redpanda-data/benthos/v4/internal/impl/pure.(*Branch).createResult(0xc00243d8c0, {0x5d45170, 0xc0022328c0}, {0xc001475af0, 0x1, 0x975b00?}, {0xc001475b00, 0x1, 0x1})
	/go/pkg/mod/github.com/redpanda-data/benthos/v4@v4.28.1/internal/impl/pure/processor_branch.go:398 +0x806
github.com/redpanda-data/benthos/v4/internal/impl/pure.(*Workflow).ProcessBatch.func3({0xc001511380, 0xe}, 0x0)
	/go/pkg/mod/github.com/redpanda-data/benthos/v4@v4.28.1/internal/impl/pure/processor_workflow.go:503 +0x408
created by github.com/redpanda-data/benthos/v4/internal/impl/pure.(*Workflow).ProcessBatch in goroutine 95
	/go/pkg/mod/github.com/redpanda-data/benthos/v4@v4.28.1/internal/impl/pure/processor_workflow.go:490 +0x891
```

**Comment by AndreasBergmeier6176** [comment]
Ah, didn't use `Message.Copy` and got punished.
